student_feedback_analysis/student_feedback_analysis/urls.py
from django.contrib import admin
from django.urls import path
from users import views as users_views
from django.contrib.auth import views as auth_views
from courses import views as courses_views

urlpatterns = [
    path('',users_views.home,name='home'),
    path('admin/', admin.site.urls),
    path('register/',users_views.register,name='register'),
    path('login/',auth_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='users/logout.html'),name='logout'),
    path('profile/',users_views.profile,name='profile'),
    path('test/',users_views.test,name='test'),
    path('mystudentreport/',courses_views.mystudentreport,name='my-student-report'),
    path('subjects/<int:tid>/',courses_views.subjects,name='subjects'),
    path('subjects/<int:tid>/<int:sid>/',courses_views.subjectfeedback,name='subject-feedback'),
    path('subjects/<int:tid>/<int:sid>/<int:fid>/',courses_views.feedbackdetail,name='feedback-detail'),
    path('subjectdetail/<int:sid>/',courses_views.subjectdetail,name='subject-detail'),
    path('subjectdetail/<int:sid>/<int:uid>/studentfeedback/',courses_views.studentfeedback,name='student-feedback'),
    path('subjectdetail/<int:sid>/<int:uid>/studentreport/',courses_views.studentreport,name='student-report'),
    path('subjectdetail/<int:sid>/myfeedback/',courses_views.myfeedback,name='myfeedback'),
    path('subjectdetail/<int:sid>/myfeedback/profreport',courses_views.profreport,name='profreport'),
    path('subjectdetail/<int:sid>/myfeedback/coursereport',courses_views.coursereport,name='coursereport'),
    path('subjectdetail/<int:sid>/myfeedback/newform/',courses_views.newform,name='newform'),
    path('subjectdetail/<int:sid>/myfeedback/<int:fid>/formreport/',courses_views.formreport,name='formreport'),
    path('subjectdetail/<int:sid>/myfeedback/<int:fid>/deleteform/',courses_views.deleteform,name='deleteform'),
    path('subjectdetail/<int:sid>/myfeedback/<int:fid>/editform/',courses_views.editform,name='editform'),
    path('subjectdetail/<int:sid>/myfeedback/<int:fid>/upload/',courses_views.upload,name='upload'),
    path('subjectdetail/<int:sid>/myfeedback/<int:fid>/deletedraft/',courses_views.deletedraft,name='deletedraft'),
    path('subjectdetail/<int:sid>/myfeedback/<int:fid>/editdraft/',courses_views.editdraft,name='editdraft'),
    path('subjectdetail/<int:sid>/myfeedback/<int:fid>/formreport/',courses_views.formreport,name='formreport'),
    path('subjectdetail/<int:sid>/myfeedback/<int:fid>/editform/<int:fqid>/deletequestion/',courses_views.deletequestion,name='deletequestion'),
    path('subjectdetail/<int:sid>/myfeedback/<int:fid>/editform/<int:fqid>/editquestion/',courses_views.editquestion,name='editquestion'),
    path('subjectdetail/<int:sid>/myfeedback/<int:fid>/editform/<int:fqid>/deletedraftquestion/',courses_views.deletedraftquestion,name='deletedraftquestion'),
    path('subjectdetail/<int:sid>/myfeedback/<int:fid>/editform/<int:fqid>/editdraftquestion/',courses_views.editdraftquestion,name='editdraftquestion'),
]

student_feedback_analysis/courses/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime
from django.utils import timezone
# Create your models here.
class Subject(models.Model):
    subject_name=models.CharField(max_length=100)
    year=models.IntegerField(default = datetime.date.today().year)
    teacher=models.ForeignKey(User, on_delete=models.CASCADE)
    enrollment_key = models.CharField(max_length=10, default="SPIT_IT")
    def __str__(self):
        return self.subject_name+"-"+str(self.year) + "-" + str(self.teacher)

class Enroll(models.Model):
    subject = models.ForeignKey("Subject",on_delete=models.CASCADE)
    student = models.ForeignKey(User,on_delete=models.CASCADE)

    def __str__(self):
        return str(self.subject)+"-"+str(self.student)

class FeedbackForm(models.Model):
    type_choices=(
      ('prof', 'Professor Feedback'),
      ('course', 'Course Feedback'),
      ('other','Other')
    )
    sem_choices=(
        ('midsem', 'Mid Semester'),
        ('endsem','End Semester'),
        ('other','Other')
    )
    feedback_type = models.CharField(max_length=100,choices=type_choices)
    sem_type = models.CharField(max_length=100,choices=sem_choices)
    subject = models.ForeignKey("Subject", on_delete=models.CASCADE)
    form_name=models.CharField(max_length = 100,default = "Feedback Form")
    def __str__(self):
        return str(self.subject)+"-"+ self.form_name 

class FormQuestion(models.Model):
    feedback_form = models.ForeignKey("FeedbackForm", on_delete=models.CASCADE)
    question = models.CharField(max_length=225)
    #draft_form = models.ForeignKey("FeedbackForm", on_delete=models.CASCADE)

    def __str__(self):
        return str(self.feedback_form)+"-Q"+ str(self.id)


class FormAnswer(models.Model):
    form_question = models.ForeignKey("FormQuestion", on_delete=models.CASCADE)
    #student = models.ForeignKey(User, on_delete=models.CASCADE)
    answer = models.TextField()
    processed_answer = models.TextField(default = "heyy")
    sentiment = models.FloatField(default=0.4)
    time_of_entry = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return str(self.form_question)+"-"+str(self.id)

class DraftForm(models.Model):
    type_choices=(
      ('prof', 'Professor Feedback'),
      ('course', 'Course Feedback'),
      ('other','Other')
    )
    sem_choices=(
        ('midsem', 'Mid Semester'),
        ('endsem','End Semester'),
        ('other','Other')
    )
    feedback_type = models.CharField(max_length=100,choices=type_choices)
    sem_type = models.CharField(max_length=100,choices=sem_choices)
    subject = models.ForeignKey("Subject", on_delete=models.CASCADE)
    form_name=models.CharField(max_length = 100,default = "Feedback Form")
    def __str__(self):
        return str(self.subject)+"-"+ self.feedback_type + "-" + self.sem_type

class DraftQuestion(models.Model):
    draft_form = models.ForeignKey("DraftForm", on_delete=models.CASCADE)
    question = models.CharField(max_length=225)
    #draft_form = models.ForeignKey("FeedbackForm", on_delete=models.CASCADE)

    def __str__(self):
        return str(self.draft_form)+"-Q"+ str(self.id)

student_feedback_analysis/courses/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from .models import Subject, FeedbackForm, FormAnswer, FormQuestion, Enroll, DraftForm, DraftQuestion
from users.decorators import unauthenticated_user, student_only, teacher_only
from django.contrib.auth.decorators import login_required
from .forms import FormFeedback, EnrollForm, StudentFeedbackForm, NewForm, NewQuestionForm, EditQuestionForm, NewDraftQuestionForm, EditDraftQuestionForm
from django.contrib import messages
import pandas as pd
import nltk
from wordcloud import WordCloud, STOPWORDS
import numpy as np
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.sentiment.vader import SentimentIntensityAnalyzer
from nltk.corpus import stopwords
stop = set(stopwords.words('english'))
words = set(nltk.corpus.words.words())
from nltk.tokenize import RegexpTokenizer
import re
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import io
import urllib,base64
from nltk.stem import WordNetLemmatizer
from nltk.stem import PorterStemmer
from django.db.models import Q
from skills.models import Skill, SkillQuestion, SkillAnswer
import datetime
import waterfall_chart


# Create your views here.
@login_required
@student_only
def subjects(request,tid):
    t=User.objects.get(id=tid)
    s=t.subject_set.all().order_by('-year')
    return render(request,'courses/subjects.html',{'s':s,'tid':tid})

@login_required
@student_only
def subjectfeedback(request,tid,sid):
    s=Subject.objects.get(id=sid)
    u=User.objects.get(id=request.user.id)
    e=Enroll.objects.all()
    flag=False
    for ei in e:
        if ei.student == u and ei.subject == s:
            flag=True
    f=s.feedbackform_set.all().order_by('-sem_type')
    if flag==True:
        #t=User.objects.get(id=tid)
        
        return render(request,'courses/formlist.html',{'tid':tid,'s':s,'f':f})
    else:
        if request.method=='POST':
            form=EnrollForm(request.POST)
            if form.is_valid() and form.cleaned_data.get('enrollment_key') == s.enrollment_key :
                #user=form.save() #this saves the details to the db
                #group=Group.objects.get(name="student")
                #user.groups.add(group)
                #username=form.cleaned_data.get('username') 
                #not form.username.data
                e = Enroll(subject=s,student=u)
                e.save()
                messages.success(request,f'Welcome')
                #note the single braces
                return render(request,'courses/formlist.html',{'tid':tid,'s':s,'f':f})
            else:
                messages.warning(request,f'Incorrect enrollment key')
        else:
    
            form=EnrollForm()
        return render(request, 'courses/enrollform.html',{'form':form})

@login_required
@student_only
def feedbackdetail(request,tid,sid,fid):
    f=FeedbackForm.objects.get(id=fid)
    #t=User.objects.get(id=tid)
    fq=f.formquestion_set.all()
    fqli=[]
    for f in fq:
        fqli.append(f.question)
    #return render(request,'courses/formquestion.html',{'tid':tid,'sid':sid,'fid':fid,'fq':fq})
    extra_questions = fqli
    lemmatizer = WordNetLemmatizer()
    form = FormFeedback(request.POST or None, extra=extra_questions)
    if form.is_valid():
        for (question, answer) in form.extra_answers():
            #save_answer(request, question, answer)
            print(question)
            print(answer)
            f=fq.filter(question=question).first()
            fa=FormAnswer(form_question=f,answer=answer)
            #remove punctuation

            tokenizer = RegexpTokenizer(r'\w+')
            tokens = tokenizer.tokenize(fa.answer)
            final=' '.join(tokens)


            #remove non english words
            a1=" ".join(w for w in nltk.wordpunct_tokenize(final)if w.lower() in words or not w.isalpha())

            #remove proper nouns
            tokenized2 = nltk.word_tokenize(a1)
            tokenized=[lemmatizer.lemmatize(w) for w in tokenized2]
            #tokenized=[ps.stem(w) for w in tokenized3]
            pos=nltk.tag.pos_tag(tokenized)
            ed=[word for word,tag in pos if tag!='NNP' and tag!='NNPs'] #removing proper nouns
            end=' '.join(ed)

            #remove stop words
            # en=[i for i in word_tokenize(end.lower()) if i not in stop] 
            # final=' '.join(en)

            #using vader classfiers
            sid=SentimentIntensityAnalyzer()
            ss=sid.polarity_scores(final)
            fa.sentiment=ss['compound']
            fa.processed_answer=final
            fa.save()
            #fa.save()

        return redirect("home")

    return render(request, "courses/formquestion.html", {'tid':tid,'sid':sid,'fid':fid,'form': form})

@login_required
@teacher_only
def subjectdetail(request, sid):
    s=Subject.objects.get(id=sid)
    e=s.enroll_set.all()
    li=[]
    for ei in e:
        u=User.objects.get(id=ei.student.id)
        li.append(u)
    return render(request, 'courses/subjectdetail.html',{'s':s,'li':li})

@login_required
@teacher_only
def studentfeedback(request, sid, uid):
    u=User.objects.get(id=uid)   
    fq=SkillQuestion.objects.all()
    fqli=[]
    i=0
    for f in fq:
        i+=1
        fqli.append(str(i)+". "+f.skill.skill_name+" -> "+f.question)
    #return render(request,'courses/formquestion.html',{'tid':tid,'sid':sid,'fid':fid,'fq':fq})
    extra_questions = fqli
    lemmatizer = WordNetLemmatizer() 
    form = StudentFeedbackForm(request.POST or None, extra=extra_questions)
    if form.is_valid():
        i=0
        q1=[]
        a1=[]
        for (question, answer) in form.extra_answers():
            i+=1
            i%=3
            
            if i==1:
                li=question.split("-> ")
                question=li[1]
           
            q1.append(question)
            a1.append(answer)
            if i==0:
                print(q1)
                print(a1)
                if a1[1]=='' and a1[2]=='':
                    pass
                else:
                                   
                    ssid=SentimentIntensityAnalyzer()
                    ss=ssid.polarity_scores(a1[1])
                    # f.sentiment=ss['compound']
                    fa=SkillAnswer(question=SkillQuestion.objects.filter(question=q1[0]).first(),yes_or_no=a1[0],student=u,answer=a1[1],tags=a1[2],sentiment=ss['compound'])
                    fa.save()
                    #print("hello")
                q1=[]
                a1=[]
        return redirect('subject-detail', sid=sid)
    return render(request, 'courses/studentform.html',{'u':u,'form':form, 'sid' : sid})

def printstudentreport(uid):
    taggedWords = []
    pos = []
    neg = []
    s = User.objects.get(id = uid)
    for ans in SkillAnswer.objects.filter(student = s):#filter(date.year == datetime.date.today().year):
        if (ans.date.year == datetime.date.today().year):
            temp = ans.tags.split(',')
            for t in temp:
                taggedWords.append(t)
        
    sentimentanalyzer=SentimentIntensityAnalyzer()
    # print(taggedWords)
    for j in taggedWords:
        if((sentimentanalyzer.polarity_scores(j))['compound']>0.3):
            pos.append(j)
        if((sentimentanalyzer.polarity_scores(j))['compound']<0.0):
            neg.append(j)
    pl = ' '.join(pos)
    nl = ' '.join(neg)

    #positive wc
    wordcloud = WordCloud(background_color='white',
    max_words=200,max_font_size=80,random_state=42).generate(pl)
    plt.figure()
    plt.tight_layout()
    fig=plt.imshow(wordcloud)
    plt.axis('off')
    fig2=plt.gcf()
    buf2=io.BytesIO()
    fig2.savefig(buf2, format="png",bbox_inches='tight')
    buf2.seek(0)
    string2=base64.b64encode(buf2.read())
    uri2=urllib.parse.quote(string2)
    #urilist2.append(uri2)
    plt.close()

    #negative wc
    wordcloud = WordCloud(background_color='white',
    max_words=200,max_font_size=80,random_state=42).generate(nl)
    wordcloud.recolor(color_func = grey_color_func)
    plt.figure()
    plt.tight_layout()
    fig=plt.imshow(wordcloud)
    plt.axis('off')
    fig3=plt.gcf()
    buf3=io.BytesIO()
    fig3.savefig(buf3, format="png",bbox_inches='tight')
    buf3.seek(0)
    string3=base64.b64encode(buf3.read())
    uri3=urllib.parse.quote(string3)
    plt.close()


    s = User.objects.get(id = uid)
    dictY = {}
    sa = SkillAnswer.objects.filter(student = s).order_by('date')
    for ans in sa:
        if ans.date.year in dictY:
            dictY[ans.date.year] += ans.sentiment
        else:
            dictY[ans.date.year] = ans.sentiment
    a = list(dictY.values())
    #a[0]=1.5
    for i in range(1,len(a)):
        a[i]=a[i]-a[i-1]

    b = [float(x) for x in list(dictY.keys())]
    #a=[0,1,2]
    print(a)
    print(b)
    buf=io.BytesIO()
    tempVar=waterfall_chart.plot(b,a).savefig(buf, format="png",bbox_inches='tight')
    #fig.show()
    buf.seek(0)
    string=base64.b64encode(buf.read())
    uri4=urllib.parse.quote(string)
    #tempVar.close()
    plt.close()


    #line
    all_s=Skill.objects.all()
    student=User.objects.get(id=uid)
    #set_subjs=set()
    s_to_print=[]
    for s in all_s: 
        diction={}
        print(s.skill_name)
        for q in SkillQuestion.objects.filter(skill=s):
            ans=SkillAnswer.objects.filter(student=student)
            ans=ans.filter(question=q)
            #ans=ans.order_by('date')
            for a in ans:
                # print(a.question.skill)
                print(a.answer)
                print(a.date)
                #print(" ")
                if a.date.year not in diction:
                    diction[a.date.year]=[0.0,0.0,0.0,0.0]
                if a.date.month <=6:
                    diction[a.date.year][0]+=a.sentiment
                    diction[a.date.year][1]+=1
                else:
                    diction[a.date.year][2]+=a.sentiment

student_feedback_analysis/courses/templates/courses/coursereport.html
{% extends "users/base.html" %}
{% block content %}
<div style="background-color:beige;padding:10px;border:3px solid black;">
    <h1 style="text-align:center">Cumulative report - Course - {{ s.subject_name }} {{ s.year }}</h1><br><br>
    <div class="container3">
        <h2 style="text-align:center">General Sentiment Ratio</h2>
        <div>
            <img src="data: image/png;base64,{{ uri }}" style="margin-left:10%"class="iconDetails">
        </div>
    
        <h3 >Total responses = {{ total }}</h3>
        <h4 >Positive responses = {{ positives }}</h4>
        <h4 >Neutral responses = {{ neutrals }}</h4>
        <h4 >Negative responses = {{ negatives }}</h4>
    </div>
    <br><br><br><br><br><br><br><br><br><br><br><br><br><br>
    <h2 style="text-align:center">Wordclouds</h2>
    
    <div class="row2">
        <div class="column2">

            <img src="data: image/png;base64,{{ urip }}" style="width:93%;">
            <figcaption><h3 style = "text-align:center;">Positive</h3></figcaption>
        </div>
        <div class="column2">
            <img src="data: image/png;base64,{{ urin }}" style="margin-left:50px;width:91%;">
            <figcaption><h3 style="margin-left:50px;text-align:center;" >Negative</h3></figcaption>
        </div>
    </div>
   
    
    <br><br>
    <h2 style="text-align:center">Course Wise Analysis</h2>
    <img src="data: image/png;base64,{{ uri3 }}" style="margin-left:20%">
    <br><br><br>
    <h2 style="text-align:center">Sentiments Over Time</h2>
    <img src="data: image/png;base64,{{ uri4 }}" style="margin-left:20%"><br><br>
{% endblock content %}

student_feedback_analysis/courses/templates/courses/editdraft.html
{% extends "users/base.html" %}
{% load crispy_forms_tags %}
{% block content %}

<form method="POST">
	{% csrf_token %}
	<fieldset class="form-group">

		{{ form|crispy }}
	</fieldset>
	<button class="btn btn-outline-info" style="float: right;"type="submit">Add question</button>
</form>
<br><br>
    <h3>Edit Questions</h3>
    
    {% for fi in fq %}
    <a class="btn btn-outline-danger" href ="{% url 'deletedraftquestion' s.id f.id fi.id %}" style="float: right;margin-left:20px;">Delete</a>
    <a class="btn btn-outline-info" href ="{% url 'editdraftquestion' s.id f.id fi.id %}" style="float: right;margin-left:20px;">Edit</a>
    <h3><a class="article-title" href="#">{{ fi.question }}</a></h3>
    {% endfor %}
{% endblock content %}

student_feedback_analysis/courses/templates/courses/editdraftquestion.html
{% extends "users/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Edit Question</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Edit</button>
            </div>
        </form>
    </div>
{% endblock content %}

student_feedback_analysis/courses/templates/courses/editform.html
{% extends "users/base.html" %}
{% load crispy_forms_tags %}
{% block content %}

<form method="POST">
	{% csrf_token %}
	<fieldset class="form-group">

        {{ form|crispy }}
        <button class="btn btn-info" style="float: right;"type="submit">Add question</button>
	</fieldset>
	
</form>
<br><br>
<div style="background-color:beige;padding:10px;border:3px solid black;">
    <u><h3 style="text-align: center;">Edit Questions</h3></u>
    
    {% for fi in fq %}
    <a class="btn btn-outline-danger" href ="{% url 'deletequestion' s.id f.id fi.id %}" style="float: right;margin-left:20px;">Delete</a>
    <a class="btn btn-outline-info" href ="{% url 'editquestion' s.id f.id fi.id %}" style="float: right;margin-left:20px;">Edit</a>
    <h3><a class="article-title" href="#">{{ fi.question }}</a></h3>
    {% endfor %}
    </div>
{% endblock content %}

student_feedback_analysis/courses/templates/courses/editquestion.html
{% extends "users/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Edit Question</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Edit</button>
            </div>
        </form>
    </div>
{% endblock content %}

student_feedback_analysis/courses/templates/courses/enrollform.html
{% extends "users/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Enrollment key required!</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Submit</button>
            </div>
        </form>
    </div>
{% endblock content %}

student_feedback_analysis/courses/templates/courses/formlist.html
{% extends "users/base.html" %}
{% block content %}
<div style="background-color:beige;padding:10px;border:3px solid black;">
    <u><h2 style="text-align: center;">Feedback forms for {{ s.subject_name}} {{ s.year }}</h2></u>
    <br><br>
    {% for fi in f %}
    <a class="btn btn-outline-info" href ="{% url 'feedback-detail' tid s.id fi.id %}" style="float: right;margin-left:20px;">Fill form</a>
    <h3><a class="article-title" href="#"> {{ fi.form_name }} </a></h3>
    <br>
    {% endfor %}
</div>
{% endblock content %}

student_feedback_analysis/courses/templates/courses/formreport.html
{% extends "users/base.html" %}
{% block content %}
<div style="background-color:beige;padding:10px;border:3px solid black;">
    <u><h1 style="text-align: center;">{{ fi.get_feedback_type_display }} {{ fi.get_sem_type_display }}</h1></u><br><br>
    <div class="container3">
        <h2 style="text-align: center;">General Sentiment Ratio</h2>
        <div>
            <img src="data: image/png;base64,{{ data }}"  style="margin-left:20%" class="iconDetails">
        </div>
        <div style="margin-left:25px;margin-top:50px;">
            <h3 >Total responses = {{ total }}</h3>
            <h4 >Positive responses = {{ positives }}</h4>
            <h4 >Neutral responses = {{ neutrals }}</h4>
            <h4 >Negative responses = {{ negatives }}</h4>
        </div>
        
    </div>
    <br><br><br><br><br><br><br><br><br><br><br><br><br><br>
    <h2 style="text-align: center;"">Wordclouds Positive VS Negative</h2><br>

    {% for uril,uril2 in urilistzip %}
    
    <h3 style="text-align: center;">{{ uril }}</h3>
    <br>
    <div class="row2">
        <div class="column2">

            <img src="data: image/png;base64,{{ uril2.positive }}" style="width:93%;">
            <figcaption style = "text-align:center;"><h3 style="text-align: center;">Positive</h3></figcaption>
        </div>
        <div class="column2">
            <img src="data: image/png;base64,{{ uril2.negative }}" style="margin-left:50px;width:91%;">
            <figcaption><h3 style="margin-left:30px;text-align: center;" >Negative</h3></figcaption>
        </div>
    </div>
    <br><br>
    {% endfor %}
    <br><br><br>
    <h2 style="text-align: center;">Question Wise Sentiments</h2>
    <br><br>
    <div style = "float:right;">
        <br>
        <h3>Key:</h3>
        {% for f in finalkey %}
        <h4>{{ f }}</h4>
    {% endfor %}
    
    </div>
    <img src="data: image/png;base64,{{ uri4 }}"width="50%" height="15%">
</div>
    
    
{% endblock content %}

student_feedback_analysis/courses/templates/courses/myfeedback.html
{% extends "users/base.html" %}
{% block content %}  

<a class="btn btn-info" href ="{% url 'coursereport' s.id %}" style="float: right;margin-left:20px;">Cumulative report - Course</a>
<a class="btn btn-info" href ="{% url 'profreport' s.id %}" style="float: right;margin-left:20px;">Cumulative report - Professor</a>
<a class="btn btn-info" href ="{% url 'newform' s.id %}" style="float: right;margin-left:20px;">Create new form</a>
<br><br>
<div style="background-color:beige;padding:10px;border:3px solid black;">
    <h2 style="text-align: center;"><u>My Forms</u></h2>
    {% for fi in f %}
    <a class="btn btn-outline-info" href ="{% url 'formreport' s.id fi.id %}" style="float: right;margin-left:20px;">View report</a>
    <a class="btn btn-outline-danger" href ="{% url 'deleteform' s.id fi.id %}" style="float: right;margin-left:20px;">Delete this form</a>
<a class="btn btn-outline-info" href ="{% url 'editform' s.id fi.id %}" style="float: right;margin-left:20px;">Edit this form</a>
    
    <h3><a class="article-title" href="#">{{ fi.form_name }} </a></h3>
    {% endfor %}
    <br>
    <h2 style="text-align: center;"><u>Drafts</u></h2>
    {% for fi in d %}
    <a class="btn btn-outline-info" href ="{% url 'upload' s.id fi.id %}" style="float: right;margin-left:20px;">Upload form</a>
    <a class="btn btn-outline-danger" href ="{% url 'deletedraft' s.id fi.id %}" style="float: right;margin-left:20px;">Delete this form</a>
<a class="btn btn-outline-info" href ="{% url 'editdraft' s.id fi.id %}" style="float: right;margin-left:20px;">Edit this form</a>
    
    <h3><a class="article-title" href="#">{{ fi.form_name }} </a></h3>
    {% endfor %}
</div>
    
{% endblock content %}

student_feedback_analysis/courses/templates/courses/newform.html
{% extends "users/base.html" %}
{% load crispy_forms_tags %}
{% block content %}    
    
    <div class="content-section">
        <form method="POST" action =".">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Create new form</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Submit</button>
               
            </div>
            
        </form>
        
    </div>
{% endblock content %}